### ISSUE TITLE
transfer content of v 1.6 from docx to adoc

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-improve#1]

**Comment by feststelltaste** [comment]
Which language version? I guess the one in German?

**Comment by gernotstarke** [comment]
The iSAQB decided to be "English-first" - that's why I propose to keep the advanced curricula in EN (maybe both)

https://www.isaqb.org/wp-content/uploads/2017/11/isaqb-curriculum-advanced-module-IMPROVE-1.6_englisch_final.pdf

**Comment by gernotstarke** [comment]
- [ ] LG-by-LG check of content (4-eye principle)
- [ ] Tag ("freeze") V1.6 - all further updates shall go into V1.7.0

**Comment by feststelltaste** [comment]
Both language versions of the migrated AsciiDoc version tagged with v1.6.1. Should do it.
