### ISSUE TITLE
split recommended timing in "teaching" and "exercise"

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-improve#21]
as done in Req4Arc:

![image](https://user-images.githubusercontent.com/1233990/78274186-1a562080-7510-11ea-8f96-8bf225c00ec4.png)

**Comment by gernotstarke** [comment]
Tabellenstruktur vorbereitet (in DE Version ist die fertig, muss in EN noch nachgetragen werden)

**Comment by feststelltaste** [comment]
For all sections, the time specification for exercises is "0 minutes". I suggest **deleting the time information** for the exercises. Exercises should be integrated by default. This fits also to the sentence in "Duration, Teaching Method and Further Details": 

> In particular, the curriculum provides no specifications on the nature of the examples and exercises.

This would give training providers enough freedom to integrate and choose exercises that fit their style.

**Comment by gernotstarke** [comment]
I suggest keeping the information on training/exercise, as to give trainers a hint where we (curriculum maintainers) expect exercises.

That still leaves freedom... as nobody can or will inspect your specific training, but new trainers/training-providers get a hint on how much exercises they should plan for...

**Comment by feststelltaste** [comment]
OK, I went through my training material and came up with the following:

| Content | Original | Theory | Exercises |
| --- | --- | --- | --- |
| 1. Foundations | 120 | 105| 15 |
| 2. Analysis of current situation | 210 | 150 | 60 |
| 3. Estimation of problems and solution approaches | 90 | 60 | 30 |
| 4. Long term improvement planning | 120 | 90 | 30 |
| 5. Typical improvement approaches | 360 | 255 | 105 |
| 6. Improvement examples | 180 | 60 | 120 |
| | ||
| Sum | 1080 (18h) | 720 (12h) | 360 (6h) |

What do you think?

**Comment by gernotstarke** [comment]
awesome, please incorporate that into the curriculum. Great starting point for others!!
