### ISSUE TITLE
More time for chapter "Estimate and Assess"

### ISSUE THREAD

**Issue by hoch4** [isaqb-org/curriculum-improve#32]
The suggested timeframe for this chapter is 90 minutes.
The time should be longer and there should be time exercises.
---
#page:03-module-block-3/01-duration-terms.adoc

**Comment by feststelltaste** [comment]
Proposed new time distribution to @gernotstarke today. Current times where taken from the main-Branch which already includes some time for exercising. How does that look like?

The two main ideas are:

- decrease time for "improvement approaches" and  "improvement examples" to get more time for "assess" and "estimate"
- increase the exercise time for each section for more hands-on activities during each section

|Section|Teaching Current|Exercises Current|All Current|Teaching Future|Exercises Future|All Future|
|---|---|---|---|---|---|---|
|1. Foundations|105|15|120|60|20|80|
|2. Analysis of current situation|150|60|210|240|75|315|
|3. Estimation of problems and solution approaches|60|30|90|120|60|180|
|4. Long term improvement planning|90|30|120|90|30|120|
|5. Typical improvement approaches|255|105|360|180|100|280|
|6. Improvement examples|60|120|180|30|75|105|
||||||||
|Sum in minutes|720|360|1080|720|360|1080|
|Sum in hours|12|6|18|12|6|18|

**Comment by gernotstarke** [comment]
I like that change, +1

**Comment by programming-wolf** [comment]
I also approve of the changes. I also like the reduction of time in the foundation section.
