### ISSUE TITLE
Extend and update reference list

### ISSUE THREAD

**Issue by hoch4** [isaqb-org/curriculum-improve#36]
A more comprehensive and up-to-date literature would help participants gain a deeper understanding of the topic.

Here are some ideas:
- The curriculum references the first edition of the refactoring book "Refactoring: Improving the Design of Existing Code". Update the reference to the second edition that was [released in 2018](https://www.martinfowler.com/books/refactoring.html).
- Add the book “Object-Oriented Reengineering Patterns” to the list of references. It is now available for free at the following URL: https://oorp.github.io./
- Add more recent literature to the references, e.g. Newman, S. (2020). Monolith to microservices: Evolutionary patterns to transform your monolith. O’Reilly Media, Inc. , ISBN: 9781492047841

---
#page:99-references/00-references.adoc

**Comment by feststelltaste** [comment]
related to #39 and #40

**Comment by feststelltaste** [comment]
closed because it will be addressed with #43
