### ISSUE TITLE
ensure important terms are defined in iSAQB glossary

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-improve#37]
for a first version some definitions could be included in the curriculum itself.

**Comment by feststelltaste** [comment]
I like the idea of a glossary within the curriculum, but don't see it as high priority for the 2024 release. Currently, we work with brief explanations and examples if there might be a potential for misunderstanding regarding terms, so it's good enough for now.

And I don't like the idea of putting the terms in the iSAQB glossary. It already mixes terms from Foundation Level with iSAQB association specific terminology. Putting in terms from Advanced Level modules would worsen the situation IMHO.

**Comment by programming-wolf** [comment]
The iSAQB glossary already contains terms from several advanced modules. 🙂  Its intention is indeed to define all the important terms of foundation and advanced (and maybe even expert) level and link to them from the curriculum.

**Comment by gernotstarke** [comment]
will close this here -as currently nobody is actively working on it, and  there is no agreed-upon terminology either. The glossary will be used for FOUNDATION terms in the near future.
