### ISSUE TITLE
Add improvement ideas from "Domain-Driven Transformation"

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-improve#39]

**Comment by feststelltaste** [comment]
Parts of this issue were covered with #48 by adding "Understanding the current state of business processes and (sub-)domains" to LG 2-2. Also, a reference to the book was added to the German version of the curriculum.

Is this already good for now or do we need to dig deeper into the book's content?

**Comment by programming-wolf** [comment]
If it is a learning goal in the document already or part of one, I think we're fine.
We don't have to create a perfect template for the training. 😁

**Comment by gernotstarke** [comment]
good enough imho
