### ISSUE TITLE
add improvement ideas from Nick Tune "Architecture Modernization"

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-improve#40]

**Comment by feststelltaste** [comment]
Tried to cover major points from Nick Tune's ideas by adding within

- LG 2-2:
  - Understanding the current state of business processes and (sub-)domains
- LG 3-1:
  - Utilize already approved budgets for strategic initiatives to align and connect improvement efforts with these priorities.

Albeit there are many other nice ideas (like, of course, Wardley Maps and more ideas towards product orientation and team organization), I think they need to be covered in other trainings or even are already covered (e.g., in iSAQB DDD)
