### ISSUE TITLE
update readme to reflect IMPROVE

### ISSUE THREAD

**Issue by gernotstarke** [isaqb-org/curriculum-improve#7]
currently it's partially copied from the template...

**Comment by feststelltaste** [comment]
I would suggest to only change the heading "How to use this template" to "How to build this document". I left out the other content from the "advanced-template" intentionally to avoid duplication.

**Comment by programming-wolf** [comment]
Parts of the README are supposed to stay the same across all advanced curricula.

**Comment by gernotstarke** [comment]
### the constant parts across several curricula should be (imho):

- [ ] where to download the generated docs 
- [ ] how to build
- [ ] how to contribute
- [ ] release process
- [ ] iSAQB contact info
- [ ] license and copyright

### sections in readme with identical title but specific content

- [ ] maintainers
- [ ] contributors

I open a corresponding issue in the "advanced-template" repo :-)

**Comment by gernotstarke** [comment]
good enough for now, closed.
